#!/usr/bin/env bash

APP_NAME="TREvoSim"
DMG_FILE_NAME="${APP_NAME}-Installer.dmg"
VOLUME_NAME="${APP_NAME} Installer"
SOURCE_FOLDER_PATH="../../build/Qt_6_7_2_for_macOS-Release/deploy/"

if [[ -e ../../create-dmg ]]; then
  # We're running from the repo
  CREATE_DMG=../../create-dmg
elif [[ -e /opt/homebrew/bin/create-dmg ]]; then
  # We're running from homebrew
  CREATE_DMG=/opt/homebrew/bin/create-dmg
else
  # We're running from an installation under a prefix
  CREATE_DMG=../../../../bin/create-dmg
fi

echo ${DMG_FILE_NAME}

# Since create-dmg does not clobber, be sure to delete previous DMG
[[ -f "${DMG_FILE_NAME}" ]] && rm "${DMG_FILE_NAME}"

# Create the DMG
$CREATE_DMG \
  --volname "${VOLUME_NAME}" \
  --background "./installer_background.jpg" \
  --window-pos 200 120 \
  --window-size 740 400 \
  --icon-size 100 \
  --icon "${APP_NAME}.app" 200 210 \
  --hide-extension "${APP_NAME}.app" \
  --app-drop-link 600 205 \
  "${SOURCE_FOLDER_PATH}${DMG_FILE_NAME}" \
  "${SOURCE_FOLDER_PATH}"