; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{72A7A216-BC27-42AF-9887-A4F9DE82B637}
AppName=TREvoSim
AppVersion=3.0.0
AppPublisher=TREvoSim Software by Palaeoware
AppPublisherURL=https://github.com/palaeoware/trevosim/
AppSupportURL=https://github.com/palaeoware/trevosim/
AppUpdatesURL=https://github.com/palaeoware/trevosim/
DefaultDirName={pf}\Palaeoware\TREvoSim\v3.0.0
DefaultGroupName=Palaeoware\TREvoSim
ArchitecturesAllowed=x64
ArchitecturesInstallIn64BitMode=x64
LicenseFile=.\bin\LICENSE.md
OutputDir=.\build
OutputBaseFilename=TREvoSimInstaller_v3.0.0_win_x64
Compression=lzma
SolidCompression=yes
ChangesAssociations=yes
AppCopyright=Copyright (C) 2016-2024 by Russell J. Garwood, Alan R.T. Spencer and Mark D. Sutton
AppContact=palaeoware@gmail.com
AppComments=TREvoSim (The [Tr]ee [Evo]lutionary [Sim]ulator program program). More details are available in the readme for the program.
BackColor=$3e3e3e
BackColor2=$3e3e3e

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
Source: ".\bin\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\TREvoSim (v3.0.0)"; Filename: "{app}\TREvoSim.exe";

[Run]
Filename: "{app}\TREvoSim.exe"; Description: "{cm:LaunchProgram,TREvoSim}"; Flags: nowait postinstall skipifsilent
